apiVersion: batch/v1
kind: Job
metadata:
  namespace: ktwin
  name: ktwin-pole-crowd-flow-observed-device-publisher
  labels:
    app: ktwin-pole-device-publisher
spec:
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        nodetype: edge # Force the execution in RaspberryPI/ARM nodes
      containers:
      - name: ktwin-pole-crowd-flow-observed-device-publisher
        image: ghcr.io/open-digital-twin/ktwin-pole-crowd-flow-observed-device-publisher:0.1-arm64
        imagePullPolicy: Always
        env:
        - name: BROKER_ADDRESS
          value: rabbitmq.ktwin.svc.cluster.local
        - name: BROKER_PORT
          value: "1883"
        - name: BROKER_TOPIC
          value: "ktwin/real/ngsi-ld-city-crowdflowobserved/ngsi-ld-city-crowdflowobserved-001"
        - name: CLIENT_ID
          value: "ktwin-pole-crowd-flow-observed-device-publisher-001"
        - name: USERNAME
          value: ""
        - name: PASSWORD
          value: ""
        - name: FULL_TIME_FRAMES
          value: "30"
        - name: MESSAGE_PERIOD
          value: "0.2"
        - name: FULL_PERIOD
          value: "10"
        - name: PART_PERIOD
          value: "4"
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
