apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ktwin
  name: ktwin-battery-device-subscriber
  labels:
    app: ktwin-battery-device-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktwin-battery-device-subscriber
  template:
    metadata:
      name: ktwin-battery-device-subscriber
      labels:
        app: ktwin-battery-device-subscriber
    spec:
      # nodeSelector:
      #   nodetype: edge
      containers:
      - name: ktwin-battery-device-subscriber
        image: ghcr.io/open-digital-twin/ktwin-battery-device-subscriber:0.1
        imagePullPolicy: Always
        env:
        - name: BROKER_ADDRESS
          value: rabbitmq.ktwin.svc.cluster.local
        - name: BROKER_PORT
          value: "1883"
        - name: BROKER_TOPIC
          value: "ktwin/virtual/ngsi-ld-city-device/ngsi-ld-city-device-001"
        - name: CLIENT_ID
          value: "ktwin-battery-device-subscriber-001"
        - name: USERNAME
          value: "default_user_4fNTdy_ZIhc45OYITSH"
        - name: PASSWORD
          value: "yXpNW2DmTN_IZOJQtK2kO75zZ2KhImaZ"
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
