apiVersion: batch/v1
kind: Job
metadata:
  namespace: ktwin
  name: ktwin-battery-device-publisher
  labels:
    app: ktwin-battery-device-publisher
spec:
  template:
    spec:
      restartPolicy: Never
      # nodeSelector:
      #   nodetype: edge # Force the execution in RaspberryPI/ARM nodes
      containers:
      - name: ktwin-battery-device-publisher
        image: ghcr.io/open-digital-twin/ktwin-battery-device-publisher:0.1
        imagePullPolicy: Always
        env:
        - name: BROKER_ADDRESS
          value: rabbitmq.ktwin.svc.cluster.local
        - name: BROKER_PORT
          value: "1883"
        - name: BROKER_TOPIC
          value: "ktwin/real/ngsi-ld-city-device/ngsi-ld-city-device-001"
        - name: CLIENT_ID
          value: "ktwin-battery-device-publisher-001"
        - name: USERNAME
          value: ""
        - name: PASSWORD
          value: ""
        - name: N_MESSAGES
          value: "20000"
        - name: MESSAGE_PERIOD
          value: "0.5"
        - name: FULL_PERIOD
          value: "10"
        - name: PART_PERIOD
          value: "4"
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
