version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.12.2-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
        - 1883:1883
    volumes:
      - ./rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbit/plugins:/usr/lib/rabbitmq/plugins
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge