apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ktwin
  name: ktwin-pole-device-subscriber
  labels:
    app: ktwin-pole-device-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktwin-pole-device-subscriber
  template:
    metadata:
      name: ktwin-pole-device-subscriber
      labels:
        app: ktwin-pole-device-subscriber
    spec:
      containers:
      - name: ktwin-pole-device-subscriber
        image: dev.local/open-digital-twin/ktwin-pole-device-subscriber:0.1
        imagePullPolicy: Never
        env:
        - name: BROKER_ADDRESS
          value: rabbitmq.ktwin.svc.cluster.local
        - name: BROKER_PORT
          value: "1883"
        - name: BROKER_TOPIC
          value: "ktwin/virtual/city-pole/city-pole-001"
        - name: CLIENT_ID
          value: "ktwin-pole-device-subscriber-001"
        - name: USERNAME
          value: ""
        - name: PASSWORD
          value: ""
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
